### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by JagadishaIncture** [pramodkr123/ConvertWebViewToPdfDemo#8]
Hi I took RunTime Permision also for Both READ and WRITE External but evn thought it s throwing this below error

java.io.IOException: Permission denied
        at java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
        at java.io.File.createNewFile(File.java:1008)
        at android.print.PdfPrint.getOutputFile(PdfPrint.java:51)
        at android.print.PdfPrint.access$000(PdfPrint.java:10)
        at android.print.PdfPrint$1.onLayoutFinished(PdfPrint.java:24)
        at ft.onLayout(chromium-TrichromeWebViewGoogle.apk-stable-410410183:4)

**Comment by pramodkr123** [comment]
<application
  android:requestLegacyExternalStorage="true"
</application>

Put this in your manifest within <application> tag.

**Comment by JagadishaIncture** [comment]
> android:requestLegacyExternalStorage="true"
> 
> Put this in your manifest within `application `tag.

Great !! its working now after adding this line
