### ISSUE TITLE
chromium-TrichromeWebViewGoogle.aab-stable

### ISSUE THREAD

**Issue by JagadishaIncture** [pramodkr123/ConvertWebViewToPdfDemo#9]
Caused by java.lang.IllegalArgumentException: fd cannot be null
       at RA.onWrite(chromium-TrichromeWebViewGoogle.aab-stable-424007533:28)
       at android.print.PdfPrint$1.onLayoutFinished(PdfPrint.java:24)
       at RA.onLayout(chromium-TrichromeWebViewGoogle.aab-stable-424007533:4)
       at android.print.PdfPrint.print(PdfPrint.java:20)
       at com.webviewtopdf.PdfView.createWebPrintJob(PdfView.java:53)
       at com.abox.rally.orderform.WebViewActivity.savePdf(WebViewActivity.java:113)
       at com.abox.rally.orderform.WebViewActivity.onRequestPermissionsResult(WebViewActivity.java:157)
       at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8289)
       at android.app.Activity.dispatchActivityResult(Activity.java:8139)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4955)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5003)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by pramodkr123** [comment]
android:requestLegacyExternalStorage="true"
Put this in your manifest within application tag.

if not fixed then check you have provided valid path directory or file name.

**Comment by JagadishaIncture** [comment]
ConvertWebViewToPdfDemoAfter adding requestLegacyExternalStorage="true" its working till Andoeid 10 .. but in Android 11 its crashing

My package is package="com.abox.rally.oderform"

 <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="com.abox.rally.oderform.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths" />


<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path name="my_images"
        path="Android/data/com.abox.rally.oderform/files/Pictures" />
</paths>


Crash StackTrace is 

Fatal Exception: java.lang.IllegalArgumentException: fd cannot be null
       at org.chromium.android_webview.AwPdfExporter.a(SourceFile:6)
       at ams.onWrite(SourceFile:29)
       at android.print.PdfPrint$1.onLayoutFinished(PdfPrint.java:24)
       at ams.onLayout(SourceFile:8)
       at android.print.PdfPrint.print(PdfPrint.java:20)
       at com.webviewtopdf.PdfView.createWebPrintJob(PdfView.java:53)


Note : Working fine till Android 10 .. issues on Android 11

**Comment by pramodkr123** [comment]
**Add this permission in your manifest for android 11.**
<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />

**before create pdf check this permission**
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            if (Environment.isExternalStorageManager()) {
                // print pdf code here
            } else {
              //request permission
            try {
                val intent = Intent(Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION)
                intent.addCategory("android.intent.category.DEFAULT")
                intent.data = Uri.parse(String.format("package:%s", applicationContext.packageName))
                startActivityForResult(intent, 1)
            } catch (e: Exception) {
                val intent = Intent()
                intent.action = Settings.ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION
                startActivityForResult(intent, 1)
            }
         }
}


override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode==1 && Environment.isExternalStorageManager()){
                // print pdf code here
            } 
        }
    }

**Comment by JagadishaIncture** [comment]
ThankYou

**Comment by jesphinpt** [comment]
I am not using any pdf related app. It crashing in the samsung modals alone. 



Trending issuesIssues rapidly gaining momentum
--
chromium-TrichromeWebViewGoogle.aab-stable-506007033 line 106org.chromium.android_webview.AwDataDirLock.b

Trending issues
Issues rapidly gaining momentum
[chromium-TrichromeWebViewGoogle.aab-stable-506007033 line 106]
org.chromium.android_webview.AwDataDirLock.b

Fatal Exception: java.lang.RuntimeException
Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process  (pid 17722), lock owner unknown

**Comment by Deepakkast** [comment]
Getting multiple anr due to this any update on the above
